name: dobeld_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: 3.0.1
  google_fonts: 3.0.1
  iconsax: 0.0.8
  iconly: 1.0.1
  crisp: 0.3.1
  lottie: 1.4.3
  avatar_glow: 2.0.2
  auth_buttons: 3.0.0
  carousel_slider: 4.1.1
  dashed_circular_progress_bar: 0.0.4
  simple_circular_progress_bar: 1.0.2
  circle_progress_bar: 0.1.2
  sleek_circular_slider: 2.0.1
  progress_indicator: 0.2.2
  flutter_slidable: 2.0.0
  awesome_dialog: 3.0.2
  drop_down_list: 0.0.4
  dropdown_search2: 1.0.2
  date_time_picker: 2.1.0
  intl: 0.17.0
  cool_alert: 1.1.0
  favorite_button: 0.0.4
  shimmer: 2.0.0
  liquid_pull_to_refresh: 3.0.1
  skeletons: 0.0.3
  get_storage: 2.0.3
  flutter_switch: 0.3.2
  firebase_core: 2.3.0
  firebase: 9.0.3
  firebase_auth: 4.1.3
  firebase_storage: 11.0.6
  cloud_firestore: 4.1.0
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

